server:
  port: 8080
  servlet:
    context-path: /blog

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://117.72.11.162:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #本地数据库内网
    url: jdbc:mysql://172.17.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #本地数据库ip访问
    #url: jdbc:mysql://192.168.163.128:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log



